/*
 * Created on 2025-04-12 ( 18:36:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
 package eu.opensource;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring Boot entry point <br>
 * 
 * @author Telosys
 *
 */
@SpringBootApplication
public class DemoApplication {

    /**
     * Main entry point for Spring Boot starting
     * 
     * @param args
     */
    public static void main(String[] args) {
    	
        SpringApplication.run(DemoApplication.class, args);
    }

}
