/*
 * Created on 2025-04-12 ( 19:18:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
 package eu.opensource;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring Boot entry point <br>
 * 
 * @author Paolo Bertin
 *
 */
@SpringBootApplication
public class DocumentStorageApplication {

    /**
     * Main entry point for Spring Boot starting
     * 
     * @param args
     */
    public static void main(String[] args) {
    	
        SpringApplication.run(DocumentStorageApplication.class, args);
    }

}
