

/*
 * Created on 2025-04-13 ( 08:14:10 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
 package eu.opensource.repository;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;


import eu.opensource.model.Document;

/**
 * Spring Data JPA repository for entity "Document" <br> 
 * 
 * @author Paolo Bertin
 *
 */
public interface DocumentRepository extends PagingAndSortingRepository<Document, Long> {

    //List<Document> findByXxx(String xxx);
    Page<Document> findBySummary(String summary, Pageable pageable);

    Page<Document> findByFilename(String filename, Pageable pageable);

    Page<Document> findByAuthor(String author, Pageable pageable);

    Page<Document> findBySpeaker(String speaker, Pageable pageable);

    Page<Document> findByDocumentyear(Integer documentyear, Pageable pageable);




	//List<Document> findByXxxStartingWith(String xxx);

	//List<Document> findByXxxContaining(String xxx);

	//List<Document> findByYyy(BigDecimal yyy);

	//List<Document> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);

}