

/*
 * Created on 2025-04-12 ( 17:12:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
 package eu.opensource.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Document"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="document" )
public class Document implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="summary")
    private String     summary ;

    @Column(name="filename")
    private String     filename ;

    @Column(name="author")
    private String     author ;

    @Column(name="speaker")
    private String     speaker ;

    @Column(name="documentyear")
    private Integer    documentyear ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Document() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( long id ) {
        this.id = id ;
    }
    public long getId() {
        return this.id;
    }

    public void setSummary( String summary ) {
        this.summary = summary ;
    }
    public String getSummary() {
        return this.summary;
    }

    public void setFilename( String filename ) {
        this.filename = filename ;
    }
    public String getFilename() {
        return this.filename;
    }

    public void setAuthor( String author ) {
        this.author = author ;
    }
    public String getAuthor() {
        return this.author;
    }

    public void setSpeaker( String speaker ) {
        this.speaker = speaker ;
    }
    public String getSpeaker() {
        return this.speaker;
    }

    public void setDocumentyear( Integer documentyear ) {
        this.documentyear = documentyear ;
    }
    public Integer getDocumentyear() {
        return this.documentyear;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Document[");
		sb.append("id=").append(id);
		sb.append(separator).append("summary=").append(summary);
		sb.append(separator).append("filename=").append(filename);
		sb.append(separator).append("author=").append(author);
		sb.append(separator).append("speaker=").append(speaker);
		sb.append(separator).append("documentyear=").append(documentyear);
		sb.append("]");
		return sb.toString();
	}
}